import { query } from "../postgres";

export async function initCoreDb() {
  await query(`
    CREATE TABLE IF NOT EXISTS super_admins (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS admins (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS super_admin_sessions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      super_admin_id INTEGER NOT NULL,
      session_token_hash TEXT NOT NULL UNIQUE,
      created_at TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      FOREIGN KEY (super_admin_id) REFERENCES super_admins(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS admin_sessions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_id INTEGER NOT NULL,
      session_token_hash TEXT NOT NULL UNIQUE,
      created_at TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS participant_links (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_id INTEGER NOT NULL,
      token TEXT NOT NULL UNIQUE,
      status TEXT NOT NULL,
      created_at TEXT NOT NULL,
      started_at TEXT,
      completed_at TEXT,
      revoked_at TEXT,
      FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_participant_links_admin_id
      ON participant_links(admin_id);

    CREATE TABLE IF NOT EXISTS participant_sessions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_id INTEGER NOT NULL,
      link_id INTEGER NOT NULL,
      participant_code TEXT NOT NULL UNIQUE,
      age INTEGER NOT NULL,
      gender TEXT NOT NULL,
      consent_accepted BOOLEAN NOT NULL,
      current_step INTEGER NOT NULL DEFAULT 1,
      status TEXT NOT NULL,
      started_at TEXT NOT NULL,
      last_activity_at TEXT NOT NULL,
      completed_at TEXT,
      UNIQUE(link_id),
      FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
      FOREIGN KEY (link_id) REFERENCES participant_links(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_participant_sessions_admin_id
      ON participant_sessions(admin_id);

    CREATE TABLE IF NOT EXISTS session_steps (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_id INTEGER NOT NULL,
      session_id INTEGER NOT NULL,
      step_number INTEGER NOT NULL,
      stimulus_type TEXT NOT NULL,
      stimulus_label TEXT NOT NULL,
      adjustable_part_label TEXT NOT NULL,
      reference_value DOUBLE PRECISION NOT NULL,
      final_value DOUBLE PRECISION NOT NULL,
      deviation DOUBLE PRECISION NOT NULL,
      clicks_more INTEGER NOT NULL,
      clicks_less INTEGER NOT NULL,
      clicks_total INTEGER NOT NULL,
      time_spent_seconds INTEGER NOT NULL,
      created_at TEXT NOT NULL,
      UNIQUE(session_id, step_number),
      FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
      FOREIGN KEY (session_id) REFERENCES participant_sessions(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_session_steps_admin_id
      ON session_steps(admin_id);
  `);
}
