services:
  - type: web
    name: psy-method-app
    runtime: node
    region: frankfurt
    plan: 0.5c-512mb
    buildCommand: npm run deploy:build
    startCommand: npm --prefix server run start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SUPER_ADMIN_USERNAME
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
